import numpy as np
# calculate the total revanue generated by two product catogories in store

arr1 =np.array([500,600,700,550])
arr2 =np.array([450,700,800,600])
print(arr1+arr2)
print("<------------------------------------>")
# calculate the profit made by company
revenue = np.array([10000,12000,11000,10500])
expenses = np.array([4000,5000,4500,4800])
print(revenue-expenses)

print("<------------------------------------>")

#Determine the product in a store are out of stock
inventory = np.array([10, 0, 5, 0, 20, 0])


out_of_stock_indices =np.where (inventory == 0)[0]


print("Indices of out of stock products:", inventory[out_of_stock_indices])
            